image:
  registry: registry.gitlab.com
  repository: mark4501703/mark-portfolio-site
  tag: latest
  secret: my-registry-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: markortleb.com
  className: "traefik"
  tls:
    enabled: true
    secretName: markortleb-com-tls
    clusterIssuer: letsencrypt-prod